#!/usr/bin/env bash
set -euo pipefail

# Sync Supa/docs →
#   1) mkdocs-site/docs              (local MkDocs)
#   2) docs-manager/public/supa-docs (GitHub Pages content)
# Also generates (from Supa/docs — source of truth):
#   - index.md (from README.md) for MkDocs
#   - public/supa-docs/manifest.json
#   - docs-manager/src/generated/supaDocsManifest.ts  (bundled into app)

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
REPO_ROOT="$(cd "$ROOT_DIR/.." && pwd)"
SRC="$ROOT_DIR/docs"
MKDOCS_DEST="$ROOT_DIR/mkdocs-site/docs"
PAGES_DEST="$REPO_ROOT/docs-manager/public/supa-docs"
MANIFEST_JSON="$PAGES_DEST/manifest.json"
MANIFEST_TS="$REPO_ROOT/docs-manager/src/generated/supaDocsManifest.ts"

if [[ ! -d "$SRC" ]]; then
  echo "ERROR: docs source not found: $SRC" >&2
  exit 1
fi

echo "==> Syncing docs from $SRC"
mkdir -p "$MKDOCS_DEST" "$PAGES_DEST" "$(dirname "$MANIFEST_TS")"

echo "  → $MKDOCS_DEST"
# Keep generated index.md files until we recreate them below.
rsync -av --delete \
  --exclude '.DS_Store' \
  --exclude 'index.md' \
  "$SRC/" "$MKDOCS_DEST/"

echo "  → $PAGES_DEST"
# Keep generated manifest until we recreate it below.
rsync -av --delete \
  --exclude '.DS_Store' \
  --exclude 'manifest.json' \
  "$SRC/" "$PAGES_DEST/"

# MkDocs expects index.md (Material section pages). Copy from README.md.
echo "==> Preparing MkDocs index.md files"
if [[ -f "$MKDOCS_DEST/README.md" ]]; then
  cp "$MKDOCS_DEST/README.md" "$MKDOCS_DEST/index.md"
fi
find "$MKDOCS_DEST" -mindepth 1 -type d -print0 | while IFS= read -r -d '' dir; do
  if [[ -f "$dir/README.md" ]]; then
    cp "$dir/README.md" "$dir/index.md"
  fi
done

# Discover folders from SRC (source of truth), not from a sync destination.
echo "==> Generating docs-manager manifests"
export SRC MANIFEST_JSON MANIFEST_TS
python3 <<'PY'
import json
import os
import re
from pathlib import Path

src = Path(os.environ["SRC"])
manifest_json = Path(os.environ["MANIFEST_JSON"])
manifest_ts = Path(os.environ["MANIFEST_TS"])

name_map: dict[str, str] = {}
readme = src / "README.md"
if readme.exists():
    pattern = re.compile(
        r"\|\s*\[`([^`]+)`\]\([^)]+\)\s*\|\s*([^|]+)\|",
        re.MULTILINE,
    )
    for match in pattern.finditer(readme.read_text(encoding="utf-8")):
        folder_id = match.group(1).strip()
        display = match.group(2).strip()
        display = re.split(r"\s*\(", display, maxsplit=1)[0].strip()
        if folder_id and display:
            name_map[folder_id] = display

folders = []
for entry in sorted(src.iterdir(), key=lambda p: p.name.lower()):
    if not entry.is_dir() or entry.name.startswith("."):
        continue
    files = [
        str(p.relative_to(src)).replace("\\", "/")
        for p in entry.rglob("*.md")
        if p.is_file()
    ]
    if not files:
        continue
    files.sort(
        key=lambda f: (
            0 if f.endswith("/README.md") or f == "README.md" else 1,
            f.lower(),
        )
    )
    folders.append(
        {
            "id": entry.name,
            "name": name_map.get(entry.name, entry.name.replace("-", " ").title()),
            "files": files,
        }
    )

payload = {
    "generated_from": "Supa/docs",
    "folders": folders,
}

manifest_json.parent.mkdir(parents=True, exist_ok=True)
manifest_json.write_text(
    json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
    encoding="utf-8",
)

ts = (
    "/* eslint-disable */\n"
    "// AUTO-GENERATED by Supa/scripts/sync_docs_to_mkdocs.sh — do not edit.\n"
    "export type SupaDocsFolder = {\n"
    "  id: string;\n"
    "  name: string;\n"
    "  files: string[];\n"
    "};\n\n"
    "export type SupaDocsManifest = {\n"
    "  generated_from: string;\n"
    "  folders: SupaDocsFolder[];\n"
    "};\n\n"
    f"export const supaDocsManifest: SupaDocsManifest = {json.dumps(payload, ensure_ascii=False, indent=2)};\n"
)
manifest_ts.parent.mkdir(parents=True, exist_ok=True)
manifest_ts.write_text(ts, encoding="utf-8")

print(f"  wrote {manifest_json} ({len(folders)} folders)")
print(f"  wrote {manifest_ts}")
PY

echo "==> Done."
echo "    Local MkDocs:  cd Supa/mkdocs-site && mkdocs serve"
echo "    Local app:     cd docs-manager && npm run dev"
echo "    Live site:     commit + push master (CI syncs + deploys)"
