#!/usr/bin/env bash
set -euo pipefail

# Sync docs into TiTiBooks (mkdocs + docs-manager).
#
# Source of truth (edit here):
#   Mobile_PROJECT/SupaMobileApp/docs/
#
# Override if needed:
#   SUPA_DOCS_SRC=/path/to/docs ./Supa/scripts/sync_docs_to_mkdocs.sh

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
REPO_ROOT="$(cd "$ROOT_DIR/.." && pwd)"

DEFAULT_SRC="/Users/tientv/Development/Mobile_PROJECT/SupaMobileApp/docs"
FALLBACK_SRC="$ROOT_DIR/docs"
SRC="${SUPA_DOCS_SRC:-}"

if [[ -z "$SRC" ]]; then
  if [[ -d "$DEFAULT_SRC" ]]; then
    SRC="$DEFAULT_SRC"
  else
    SRC="$FALLBACK_SRC"
  fi
fi

LOCAL_MIRROR="$ROOT_DIR/docs"
MKDOCS_DEST="$ROOT_DIR/mkdocs-site/docs"
PAGES_DEST="$REPO_ROOT/docs-manager/public/supa-docs"
MANIFEST_JSON="$PAGES_DEST/manifest.json"
MANIFEST_TS="$REPO_ROOT/docs-manager/src/generated/supaDocsManifest.ts"

if [[ ! -d "$SRC" ]]; then
  echo "ERROR: docs source not found: $SRC" >&2
  exit 1
fi

ORIGIN_SRC="$SRC"
echo "==> Source of truth: $ORIGIN_SRC"
echo "==> Syncing…"
mkdir -p "$LOCAL_MIRROR" "$MKDOCS_DEST" "$PAGES_DEST" "$(dirname "$MANIFEST_TS")"

# 1) Mirror into TiTiBooks/Supa/docs (keeps repo copy up to date)
if [[ "$(cd "$ORIGIN_SRC" && pwd)" != "$(cd "$LOCAL_MIRROR" && pwd)" ]]; then
  echo "  → $LOCAL_MIRROR  (TiTiBooks mirror)"
  rsync -av --delete --exclude '.DS_Store' --exclude 'docsold' "$ORIGIN_SRC/" "$LOCAL_MIRROR/"
else
  echo "  → skip mirror (source already is $LOCAL_MIRROR)"
fi

# 2) MkDocs working copy
echo "  → $MKDOCS_DEST"
rsync -av --delete --exclude '.DS_Store' "$LOCAL_MIRROR/" "$MKDOCS_DEST/"

# 3) docs-manager public content
echo "  → $PAGES_DEST"
rsync -av --delete \
  --exclude '.DS_Store' \
  --exclude 'manifest.json' \
  "$LOCAL_MIRROR/" "$PAGES_DEST/"

# MkDocs: convert every README.md → index.md and remove README.md to avoid duplicates.
echo "==> Preparing MkDocs pages (README.md → index.md)"
export MKDOCS_DEST
python3 <<'PY'
import re
from pathlib import Path
import os

dest = Path(os.environ["MKDOCS_DEST"])
banner = (
    "<!-- AUTO-GENERATED by Supa/scripts/sync_docs_to_mkdocs.sh — DO NOT EDIT.\n"
    "     Edit Mobile_PROJECT/SupaMobileApp/docs/ then re-run the sync script. -->\n\n"
)

def rewrite_readme_links(text: str) -> str:
    text = re.sub(r"\]\((?:\./)?README\.md\)", "](./)", text)
    text = re.sub(r"\]\(([^)#]+)/README\.md(#[^)]*)?\)", r"](\1/\2)", text)
    return text

converted = 0
for readme in sorted(dest.rglob("README.md")):
    if not readme.is_file():
        continue
    index = readme.with_name("index.md")
    body = rewrite_readme_links(readme.read_text(encoding="utf-8"))
    index.write_text(banner + body, encoding="utf-8")
    readme.unlink()
    converted += 1
    print(f"  {readme.relative_to(dest)} → {index.relative_to(dest)}")

print(f"  converted {converted} README.md → index.md")
PY

# Discover folders from LOCAL_MIRROR (synced source of truth).
echo "==> Generating docs-manager manifests"
export SRC="$LOCAL_MIRROR" MANIFEST_JSON MANIFEST_TS
python3 <<'PY'
import json
import os
import re
from pathlib import Path

src = Path(os.environ["SRC"])
manifest_json = Path(os.environ["MANIFEST_JSON"])
manifest_ts = Path(os.environ["MANIFEST_TS"])

name_map: dict[str, str] = {}
readme = src / "README.md"
if readme.exists():
    pattern = re.compile(
        r"\|\s*\[`([^`]+)`\]\([^)]+\)\s*\|\s*([^|]+)\|",
        re.MULTILINE,
    )
    for match in pattern.finditer(readme.read_text(encoding="utf-8")):
        folder_id = match.group(1).strip()
        display = match.group(2).strip()
        display = re.split(r"\s*\(", display, maxsplit=1)[0].strip()
        if folder_id and display:
            name_map[folder_id] = display

folders = []
for entry in sorted(src.iterdir(), key=lambda p: p.name.lower()):
    if not entry.is_dir() or entry.name.startswith("."):
        continue
    files = [
        str(p.relative_to(src)).replace("\\", "/")
        for p in entry.rglob("*.md")
        if p.is_file()
    ]
    if not files:
        continue
    files.sort(
        key=lambda f: (
            0 if f.endswith("/README.md") or f == "README.md" else 1,
            f.lower(),
        )
    )
    folders.append(
        {
            "id": entry.name,
            "name": name_map.get(entry.name, entry.name.replace("-", " ").title()),
            "files": files,
        }
    )

payload = {
    "generated_from": "SupaMobileApp/docs",
    "folders": folders,
}

manifest_json.parent.mkdir(parents=True, exist_ok=True)
manifest_json.write_text(
    json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
    encoding="utf-8",
)

ts = (
    "/* eslint-disable */\n"
    "// AUTO-GENERATED by Supa/scripts/sync_docs_to_mkdocs.sh — do not edit.\n"
    "export type SupaDocsFolder = {\n"
    "  id: string;\n"
    "  name: string;\n"
    "  files: string[];\n"
    "};\n\n"
    "export type SupaDocsManifest = {\n"
    "  generated_from: string;\n"
    "  folders: SupaDocsFolder[];\n"
    "};\n\n"
    f"export const supaDocsManifest: SupaDocsManifest = {json.dumps(payload, ensure_ascii=False, indent=2)};\n"
)
manifest_ts.parent.mkdir(parents=True, exist_ok=True)
manifest_ts.write_text(ts, encoding="utf-8")

print(f"  wrote {manifest_json} ({len(folders)} folders)")
for folder in folders:
    print(f"    - {folder['id']}: {len(folder['files'])} file(s)")
print(f"  wrote {manifest_ts}")
PY

echo "==> Done."
echo ""
echo "  Edit docs ONLY in:  $ORIGIN_SRC"
echo "  Then run:           ./Supa/scripts/sync_docs_to_mkdocs.sh"
echo "  MkDocs preview:     cd Supa/mkdocs-site && mkdocs serve"
echo "  App preview:        cd docs-manager && npm run dev"
echo "  Live site:          commit + push master"
